import Vue from 'vue';
import empty from '@hui-pro/empty';
import errorDialog from '@hui-pro/error-dialog';
import imgPreview from '@hui-pro/img-preview';
import imgView from '@hui-pro/img-view';
import layout from '@hui-pro/layout';
import locale from '@hui-pro/locale';
import page from '@hui-pro/page';
import selectTreeOption from '@hui-pro/select-tree-option';
import tableTransfer from '@hui-pro/table-transfer';
import treeSelect from '@hui-pro/tree-select';
import vehicleNumberInput from '@hui-pro/vehicle-number-input';

Vue.use(empty);
Vue.use(errorDialog);
Vue.use(imgPreview);
Vue.use(imgView);
Vue.use(layout);
Vue.use(locale);
Vue.use(page);
Vue.use(selectTreeOption);
Vue.use(tableTransfer);
Vue.use(treeSelect);
Vue.use(vehicleNumberInput);
